server:
  port: 3000

spring:
  application:
    name: smart-light-backend
  datasource:
    url: jdbc:mysql://localhost:3306/smart_light?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: ******
    driver-class-name: com.mysql.cj.jdbc.Driver

ai:
  fabric:
    url: http://127.0.0.1:5001/predict
  flow:
    url: http://127.0.0.1:5000/detect_binary

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs